# Generated by Django 5.2.8 on 2025-11-12 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код модели')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('compatible_printers', models.TextField(blank=True, verbose_name='Совместимые принтеры')),
                ('max_refills', models.IntegerField(default=5, verbose_name='Максимальное количество заправок')),
                ('refill_instructions', models.TextField(blank=True, verbose_name='Инструкции по заправке')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('warehouse', 'Склад'), ('office', 'Офис'), ('service', 'Сервисный центр')], max_length=20, verbose_name='Тип')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрих-код')),
                ('current_status', models.CharField(choices=[('in_stock', 'На складе'), ('in_transit', 'В пути'), ('at_service', 'На заправке'), ('in_reserve', 'В резерве'), ('installed', 'Установлен'), ('disposed', 'Списан')], default='in_stock', max_length=20, verbose_name='Текущий статус')),
                ('date_of_introduction', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ввода в эксплуатацию')),
                ('refill_count', models.IntegerField(default=0, verbose_name='Количество заправок')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('working', 'Рабочий'), ('needs_repair', 'Требует ремонта'), ('refilled', 'Заправлен')], default='new', max_length=20, verbose_name='Состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartridges.cartridgemodel', verbose_name='Модель')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartridges.location', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('installation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата установки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartridges.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('receipt', 'Поступление'), ('issue_service', 'Выдача на заправку'), ('receive_service', 'Приём с заправки'), ('install', 'Установка в принтер'), ('remove', 'Снятие с принтера'), ('transfer', 'Перемещение'), ('dispose', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge', verbose_name='Картридж')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_from', to='cartridges.location', verbose_name='Откуда')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_to', to='cartridges.location', verbose_name='Куда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartridges.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='cartridge',
            name='installed_in_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartridges.printer', verbose_name='Установлен в принтере'),
        ),
        migrations.AddIndex(
            model_name='cartridge',
            index=models.Index(fields=['serial_number'], name='cartridges__serial__16010d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartridge',
            index=models.Index(fields=['current_status'], name='cartridges__current_7363fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cartridge',
            index=models.Index(fields=['barcode'], name='cartridges__barcode_3fc940_idx'),
        ),
    ]
