# Generated by Django 5.2.8 on 2025-11-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridgemodel',
            name='code',
        ),
    ]
