# Generated by Django 5.2.8 on 2025-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0002_remove_cartridgemodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
    ]
