# Generated by Django 5.2.8 on 2025-11-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0003_remove_location_address'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartridge',
            name='cartridges__barcode_3fc940_idx',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='barcode',
        ),
    ]
