# Generated by Django 4.2.15 on 2025-11-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0004_remove_cartridge_cartridges__barcode_3fc940_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расходник', 'verbose_name_plural': 'Расходники'},
        ),
        migrations.AddField(
            model_name='cartridge',
            name='consumable_type',
            field=models.CharField(choices=[('cartridge', 'Картридж'), ('drum', 'Барабан')], default='cartridge', max_length=20, verbose_name='Тип расходника'),
        ),
        migrations.AddIndex(
            model_name='cartridge',
            index=models.Index(fields=['consumable_type'], name='cartridges__consuma_515f1a_idx'),
        ),
    ]
