# Generated by Django 5.2.8 on 2025-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0005_alter_cartridge_options_cartridge_consumable_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='is_inkjet',
            field=models.BooleanField(default=False, verbose_name='На чернилах'),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('laser', 'Лазерный'), ('inkjet', 'Струйный'), ('multifunction', 'МФУ')], default='laser', max_length=20, verbose_name='Тип принтера'),
            preserve_default=False,
        ),
    ]
